public class Exercicio_03 {
public int inverter(int num, int tot){
    if(num==0){//CONDIÇÃO DE PARADA 
        return tot;//SE O NUMERO DIGITADO PELO USUÁRIO FOR '0' ELE IRÁ RETORNAR O TOT QUE SERÁ 0.
    }else
        return inverter(num / 10, tot * 10 + num % 10);//INICIALMENTE O NUMERO DIGITADO PELO USUÁRIO É DIVIDIDO POR 10 PARA QUE SEJA TIRADO O ULTIMO DÍGITO DELE, EM SEGUIDA O TOT(QUE SERÁ O RESULTADO DA OPERAÇÃO INVERTIDA) É CALCULADA A PARTIR DA MULTIPLICAÇÃO POR 10 SOMADO COM O RESTO DA DIVISÃO DO NÚMERO POR 10.
}//EX:SUPONHA QUE O USUÁRIO DIGITOU '1234':   1234/10=123, TOT=0 *10 + 4'RESTO DA DIVISÃO'== 4; ==>  123/10=12, TOT=4 * 10 + 3'RESTO DA DIVISÃO' == 43...
}
